<?php

namespace Modules\Admin\Tests\Feature\Media;

use App\Models\Media\Media;
use Illuminate\Http\Response;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class FeatureTestForMediaTest extends TestCase
{

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model
     */
    public $media;

    private $headers = [
        'contentType' => "application/json; charset=utf-8"
    ];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->media = Media::factory()->create();
    }

    public function test_media_upload_works()
    {
        $file = UploadedFile::fake()->image('file.png', 600, 600);
        $response = $this->post(route('media.store'),[
            'file' => $file
        ]);
        $response->assertStatus(200);

        unlink($response->json()['disk_location']);
    }

    public function testMediaList()
    {
        $this->get(route('media.index'))
            ->assertSee($this->media->english_title);
    }

    public function testMediaListIsResponseAsJson()
    {
        $this->get(route('media.index'),$this->headers)
            ->assertSee($this->media->english_title);
    }


    public function testMediaDeleteWhenFileExists()
    {
        $this->delete(route('media.destroy', $this->media->id))
            ->assertStatus(Response::HTTP_OK);
    }

    public function testMediaShowErrorOnMediaNotFound()
    {
        $this->delete(route('media.destroy', 0))->assertStatus(Response::HTTP_NOT_FOUND);
    }
}
